# Replace this all file
name: kilol 
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  audioplayers: ^5.2.1
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animation/LoadingPage.json
    - assets/images/k.png
    - assets/images/ek.png
    - assets/images/Logo.png
    - assets/images/animals.jpg
    - assets/images/shapes.jpg
    - assets/images/imotions.webp
    - assets/images/sanskar.png
    - assets/images/letters/
    - assets/animation/angry.json
    - assets/animation/happy.json
    - assets/animation/sadd.json
    - assets/animation/elephant.json
    - assets/animation/Horse.json
    - assets/animation/Lion.json
    - assets/animation/dog.json
    - assets/animation/monkey.json
    - assets/animation/cat.json
    - assets/images/Vegetables.jpg
    - assets/images/fruits.jpg
    - assets/animation/
    - assets/images/
    - assets/animation/sleepy.json
    - assets/audio/try.mp3
    - assets/audio/Lion.mp3
    - assets/audio/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/animals.jpg"
  adaptive_icon_background: "#ffffff"
